server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/cloud_user?useSSL=false  # docker-compose部署时改为服务名称 mysql
    username: root
    password: nicai1993
    driver-class-name: com.mysql.jdbc.Driver
#  application:
#    name: userService
#  cloud:
#    nacos:
#      server-addr: localhost:8848 # nacos服务地址
#      discovery:
#        cluster-name: HZ  # 集群名称

mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS


#eureka:
#  client:
#    service-url: # eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka